# Generated by Django 2.1 on 2025-12-23 13:24

import colegio.Apps.SituacionFinal.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Matricula', '0002_auto_20250507_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoSituacionFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='situacion_final/archivos/', validators=[colegio.Apps.SituacionFinal.models.validate_file_extension], verbose_name='Archivo ZIP/RAR')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('total_procesados', models.IntegerField(default=0)),
                ('total_errores', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Archivo de Situaciones Finales',
                'verbose_name_plural': 'Archivos de Situaciones Finales',
            },
        ),
        migrations.CreateModel(
            name='SituacionFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.CharField(blank=True, max_length=500, null=True, verbose_name='PDF de origen')),
                ('dni_encontrado', models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI encontrado')),
                ('situacion_final', models.CharField(blank=True, max_length=100, null=True, verbose_name='Situación Final')),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matricula.Matricula', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Situación Final',
                'verbose_name_plural': 'Situaciones Finales',
            },
        ),
        migrations.AlterUniqueTogether(
            name='situacionfinal',
            unique_together={('matricula',)},
        ),
    ]
