# Generated by Django 2.1 on 2025-12-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SituacionFinal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacionfinal',
            name='cursos',
            field=models.TextField(blank=True, null=True, verbose_name='Cursos con bajo rendimiento'),
        ),
    ]
